project:
  type: book

book:
  title: "df-foundational-soft-skills"
  author: "Norah Jones"
  date: "12/19/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

