project:
  type: book

book:
  title: "Foundational Soft Skills"
  subtitle: "MACEPA Data Fellowship - Training Materials"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

