project:
  type: book

book:
  title: "Foundational Soft Skills"
  subtitle: "MACEPA Data Fellowship - Training Materials"
  chapters:
    - index.qmd
    - intro.qmd
    - story-telling.qmd
    - summary.qmd


format:
  html:
    theme:
    - cosmo
    - custom.scss
    template-partials: title-block.html
    css: include/webex.css
    include-after-body: include/webex.js
    embed-resources: true 
  pdf:
    documentclass: scrreprt
editor: visual

execute:
  freeze: auto

