name: Sync gh-pages with main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Node.js (needed for Quarto or Jekyll sites)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build Quarto site
      run: |
        quarto render  # Adjust if using a different static site generator

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Change to your output directory
